name: "Gus Wezerek's Five Favorites"
description: "Portofolioliolio"

url: "http://localhost:4000"

paginate: 10

markdown: rdiscount
permalink: none

exclude: ["*.scss", "Gruntfile.js", "*.sublime-project", "node_modules", "*.sublime-workspace", "package.json"]